# **Latihan Preprocessing Data dengan Missing Values**

## **Import library**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## **Import dataset**

In [2]:
dataset = pd.read_csv('Data_Anemia_Missing.csv')

In [3]:
print(dataset.head())

   Number Sex  %Red Pixel  %Green pixel  %Blue pixel    Hb Anaemic
0       1   M     43.2555       30.8421      25.9025   6.3     Yes
1       2   F     45.6033       28.1900      26.2067  13.5      No
2       3  F      45.0107       28.9677          NaN  11.7      No
3       4   F     44.5398       28.9899      26.4703  13.5      No
4       5  M      43.2870       30.6972      26.0158  12.4      No


In [4]:
# Hapus kolom Number yang tidak diinginkan
dataset.drop(columns=['Number'], inplace=True)

In [5]:
# Memisahkan fitur (X) dan target (y)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[['M' 43.2555 30.8421 25.9025 6.3]
 ['F' 45.6033 28.19 26.2067 13.5]
 ['F ' 45.0107 28.9677 nan 11.7]
 ['F' 44.5398 28.9899 26.4703 13.5]
 ['M ' 43.287 30.6972 26.0158 12.4]
 ['M' 45.0994 27.9645 26.9361 16.2]
 ['F' 43.1457 30.1628 26.6915 8.6]
 ['F ' nan 29.1099 27.2798 10.3]
 ['F' 45.0423 29.166 25.7918 13.0]
 ['F' 46.5143 27.4282 26.0575 9.7]
 ['F' 45.3506 29.1248 25.5246 12.6]
 ['F' 44.4062 28.9298 26.664 15.4]
 ['F' nan 30.5279 24.5079 4.8]
 ['M ' 45.0484 31.1049 23.8467 9.0]
 ['M ' 46.9942 26.0496 26.9562 14.6]
 ['M' 45.5842 nan 25.6848 14.0]
 ['F' 42.5358 30.1604 27.3039 10.0]
 ['F' 44.0957 29.9973 25.907 8.3]
 ['F' 45.7104 27.5693 26.7204 13.6]
 ['F ' 40.9365 31.9687 27.0948 9.9]
 ['F' 44.9116 30.3761 24.7123 11.6]
 ['F ' 43.4225 29.7889 26.7886 12.4]
 ['F' nan 29.8285 26.8697 12.1]
 ['F ' 47.6372 26.7953 25.5675 15.1]
 ['M' 45.6906 30.0735 24.2359 9.1]
 ['M ' 43.4098 31.2315 nan 12.9]
 ['F' 44.4252 28.7436 26.8312 14.7]
 ['M' 44.3297 28.7617 26.9086 14.1]
 ['M' 47.8913 27.0952

In [7]:
print(y)

['Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No']


In [8]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sex           104 non-null    object 
 1   %Red Pixel    97 non-null     float64
 2   %Green pixel  99 non-null     float64
 3   %Blue pixel   99 non-null     float64
 4   Hb            100 non-null    float64
 5   Anaemic       104 non-null    object 
dtypes: float64(4), object(2)
memory usage: 5.0+ KB
None


In [9]:
# periksa nilai yang hilang di setiap kolom
print(dataset.isnull().sum())

Sex             0
%Red Pixel      7
%Green pixel    5
%Blue pixel     5
Hb              4
Anaemic         0
dtype: int64


## **Membersihkan spasi pada kolom 'Sex'**

In [10]:
dataset['Sex'] = dataset['Sex'].str.strip()
X[:, 0] = dataset['Sex']

In [11]:
# Periksa nilai unik di kolom 'Sex' setelah dibersihkan
print(dataset['Sex'].unique())

['M' 'F']


In [12]:
print(X)

[['M' 43.2555 30.8421 25.9025 6.3]
 ['F' 45.6033 28.19 26.2067 13.5]
 ['F' 45.0107 28.9677 nan 11.7]
 ['F' 44.5398 28.9899 26.4703 13.5]
 ['M' 43.287 30.6972 26.0158 12.4]
 ['M' 45.0994 27.9645 26.9361 16.2]
 ['F' 43.1457 30.1628 26.6915 8.6]
 ['F' nan 29.1099 27.2798 10.3]
 ['F' 45.0423 29.166 25.7918 13.0]
 ['F' 46.5143 27.4282 26.0575 9.7]
 ['F' 45.3506 29.1248 25.5246 12.6]
 ['F' 44.4062 28.9298 26.664 15.4]
 ['F' nan 30.5279 24.5079 4.8]
 ['M' 45.0484 31.1049 23.8467 9.0]
 ['M' 46.9942 26.0496 26.9562 14.6]
 ['M' 45.5842 nan 25.6848 14.0]
 ['F' 42.5358 30.1604 27.3039 10.0]
 ['F' 44.0957 29.9973 25.907 8.3]
 ['F' 45.7104 27.5693 26.7204 13.6]
 ['F' 40.9365 31.9687 27.0948 9.9]
 ['F' 44.9116 30.3761 24.7123 11.6]
 ['F' 43.4225 29.7889 26.7886 12.4]
 ['F' nan 29.8285 26.8697 12.1]
 ['F' 47.6372 26.7953 25.5675 15.1]
 ['M' 45.6906 30.0735 24.2359 9.1]
 ['M' 43.4098 31.2315 nan 12.9]
 ['F' 44.4252 28.7436 26.8312 14.7]
 ['M' 44.3297 28.7617 26.9086 14.1]
 ['M' 47.8913 27.0952 25.0135 

## **Menghilangkan Missing Value**

In [13]:
# periksa nilai yang hilang di setiap kolom
print(dataset.isnull().sum())

Sex             0
%Red Pixel      7
%Green pixel    5
%Blue pixel     5
Hb              4
Anaemic         0
dtype: int64


In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:5])
X[:, 1:5] = imputer.transform(X[:, 1:5])

In [15]:
print(X)

[['M' 43.2555 30.8421 25.9025 6.3]
 ['F' 45.6033 28.19 26.2067 13.5]
 ['F' 45.0107 28.9677 25.46059494949495 11.7]
 ['F' 44.5398 28.9899 26.4703 13.5]
 ['M' 43.287 30.6972 26.0158 12.4]
 ['M' 45.0994 27.9645 26.9361 16.2]
 ['F' 43.1457 30.1628 26.6915 8.6]
 ['F' 45.79102474226804 29.1099 27.2798 10.3]
 ['F' 45.0423 29.166 25.7918 13.0]
 ['F' 46.5143 27.4282 26.0575 9.7]
 ['F' 45.3506 29.1248 25.5246 12.6]
 ['F' 44.4062 28.9298 26.664 15.4]
 ['F' 45.79102474226804 30.5279 24.5079 4.8]
 ['M' 45.0484 31.1049 23.8467 9.0]
 ['M' 46.9942 26.0496 26.9562 14.6]
 ['M' 45.5842 28.854034343434343 25.6848 14.0]
 ['F' 42.5358 30.1604 27.3039 10.0]
 ['F' 44.0957 29.9973 25.907 8.3]
 ['F' 45.7104 27.5693 26.7204 13.6]
 ['F' 40.9365 31.9687 27.0948 9.9]
 ['F' 44.9116 30.3761 24.7123 11.6]
 ['F' 43.4225 29.7889 26.7886 12.4]
 ['F' 45.79102474226804 29.8285 26.8697 12.1]
 ['F' 47.6372 26.7953 25.5675 15.1]
 ['M' 45.6906 30.0735 24.2359 9.1]
 ['M' 43.4098 31.2315 25.46059494949495 12.9]
 ['F' 44.4252 28.

## **Encoding data kategori (Atribut)**

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Ubah kolom 'Sex' bertipe string ke numerik menggunakan OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [17]:
# Tampilkan hasil
print(X)

[[0.0 1.0 43.2555 30.8421 25.9025 6.3]
 [1.0 0.0 45.6033 28.19 26.2067 13.5]
 [1.0 0.0 45.0107 28.9677 25.46059494949495 11.7]
 [1.0 0.0 44.5398 28.9899 26.4703 13.5]
 [0.0 1.0 43.287 30.6972 26.0158 12.4]
 [0.0 1.0 45.0994 27.9645 26.9361 16.2]
 [1.0 0.0 43.1457 30.1628 26.6915 8.6]
 [1.0 0.0 45.79102474226804 29.1099 27.2798 10.3]
 [1.0 0.0 45.0423 29.166 25.7918 13.0]
 [1.0 0.0 46.5143 27.4282 26.0575 9.7]
 [1.0 0.0 45.3506 29.1248 25.5246 12.6]
 [1.0 0.0 44.4062 28.9298 26.664 15.4]
 [1.0 0.0 45.79102474226804 30.5279 24.5079 4.8]
 [0.0 1.0 45.0484 31.1049 23.8467 9.0]
 [0.0 1.0 46.9942 26.0496 26.9562 14.6]
 [0.0 1.0 45.5842 28.854034343434343 25.6848 14.0]
 [1.0 0.0 42.5358 30.1604 27.3039 10.0]
 [1.0 0.0 44.0957 29.9973 25.907 8.3]
 [1.0 0.0 45.7104 27.5693 26.7204 13.6]
 [1.0 0.0 40.9365 31.9687 27.0948 9.9]
 [1.0 0.0 44.9116 30.3761 24.7123 11.6]
 [1.0 0.0 43.4225 29.7889 26.7886 12.4]
 [1.0 0.0 45.79102474226804 29.8285 26.8697 12.1]
 [1.0 0.0 47.6372 26.7953 25.5675 15.1]
 [

## **Encoding data kategori (Label)**

In [18]:
from sklearn.preprocessing import LabelEncoder
# Encoding target "Anaemic" menggunakan LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
print(y)

[1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0
 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0]


## **Membagi dataset ke dalam training set dan test set**

In [20]:
from sklearn.model_selection import train_test_split

# test_size = 0.2 berarti 20% dari data akan digunakan untuk pengujian
# random_state = 0 untuk memastikan hasil yang konsisten setiap kali kode dijalankan
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [21]:
print(X_train)

[[1.0 0.0 42.5892 31.5405 25.8703 9.0]
 [1.0 0.0 44.5398 28.9899 26.4703 13.5]
 [0.0 1.0 44.72 28.0357 27.2443 14.0]
 [1.0 0.0 43.1335 28.854034343434343 27.5206 10.4]
 [0.0 1.0 53.9113 26.3455 19.7433 14.5]
 [1.0 0.0 43.1457 30.1628 26.6915 8.6]
 [0.0 1.0 46.7979 28.1768 25.0253 14.0]
 [1.0 0.0 50.4801 25.1403 24.3796 11.5]
 [1.0 0.0 44.3346 30.4043 25.2611 8.0]
 [0.0 1.0 43.4837 30.7106 25.8057 12.142999999999997]
 [0.0 1.0 48.3681 26.922 24.7099 12.5]
 [1.0 0.0 46.3745 28.882 24.7435 10.7]
 [0.0 1.0 41.133 32.3681 25.46059494949495 10.0]
 [1.0 0.0 47.1003 28.3195 24.5801 12.4]
 [0.0 1.0 44.3297 28.7617 26.9086 14.1]
 [1.0 0.0 45.7104 27.5693 26.7204 13.6]
 [1.0 0.0 50.3562 29.2206 20.4232 11.9]
 [0.0 1.0 48.8763 29.4806 21.6431 12.142999999999997]
 [1.0 0.0 43.9224 29.8338 26.2437 12.1]
 [0.0 1.0 47.7549 26.2457 25.9994 15.2]
 [1.0 0.0 43.5706 29.8094 26.6199 12.2]
 [1.0 0.0 45.6033 28.19 26.2067 13.5]
 [1.0 0.0 49.5899 28.9754 21.4347 9.9]
 [0.0 1.0 46.7628 28.018 25.2192 15.2]
 [0

In [22]:
print(X_test)

[[1.0 0.0 44.4252 28.7436 26.8312 14.7]
 [1.0 0.0 45.0693 28.854034343434343 25.0801 10.0]
 [1.0 0.0 45.0107 28.9677 25.46059494949495 11.7]
 [1.0 0.0 45.8483 27.2043 26.9474 15.5]
 [1.0 0.0 46.255 27.2758 26.4692 11.0]
 [0.0 1.0 48.5356 26.4917 24.9727 15.6]
 [1.0 0.0 42.5358 30.1604 27.3039 10.0]
 [1.0 0.0 49.9999 29.286 20.7141 14.5]
 [0.0 1.0 49.1475 28.2711 22.5813 12.6]
 [0.0 1.0 46.9428 27.2219 25.8353 13.3]
 [0.0 1.0 44.1609 28.854034343434343 26.2399 9.5]
 [1.0 0.0 51.5802 28.2678 20.152 13.2]
 [0.0 1.0 44.0418 28.5164 27.4418 11.9]
 [0.0 1.0 45.0484 31.1049 23.8467 9.0]
 [1.0 0.0 45.79102474226804 29.1099 27.2798 10.3]
 [0.0 1.0 44.2572 29.6578 26.085 12.9]
 [1.0 0.0 45.79102474226804 29.8285 26.8697 12.1]
 [0.0 1.0 45.6906 30.0735 24.2359 9.1]
 [0.0 1.0 45.4434 28.3301 26.2265 14.5]
 [1.0 0.0 45.0423 29.166 25.7918 13.0]
 [0.0 1.0 44.9526 28.4671 26.5803 13.1]]


In [23]:
print(y_train)

[1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0
 0 0 0 1 1 0 1 0 0]


In [24]:
print(y_test)

[0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0]


## **Feature Scaling**

In [25]:
from sklearn.preprocessing import StandardScaler
# Menerapkan standarisasi pada fitur numerik (mulai dari kolom ke-3)
sc = StandardScaler()
X_train[:, 2:] = sc.fit_transform(X_train[:, 2:]) 
X_test[:, 2:] = sc.transform(X_test[:, 2:])

In [26]:
print(X_train)

[[1.0 0.0 -1.0976673867970033 1.6269741177723351 0.1995244309102708
  -1.1992823461422857]
 [1.0 0.0 -0.4188415864021542 0.06772252906105294 0.5073579049104793
  0.5343883158649887]
 [0.0 1.0 -0.35613041587454664 -0.5156060469400072 0.9044630863707459
  0.7270183894213526]
 [1.0 0.0 -0.9082462429669428 -0.015335865376060001 1.0462204011478429
  -0.6599181401844669]
 [0.0 1.0 2.8425220906204656 -1.5488715669117008 -2.9439683944218498
  0.9196484629777164]
 [1.0 0.0 -0.9040005366382147 0.7847484007773017 0.6208458456585556
  -1.353386404987377]
 [0.0 1.0 0.3669968939995719 -0.42934775509998363 -0.23400771164002118
  0.7270183894213526]
 [1.0 0.0 1.6484345861014447 -2.285643312663617 -0.5652878352432456
  -0.2361319783604666]
 [1.0 0.0 -0.4902529748164992 0.9323839605176655 -0.1130291563579408
  -1.5845424932550134]
 [0.0 1.0 -0.7863735908095161 1.119633533803271 0.16638102687624912
  0.011590296233016193]
 [0.0 1.0 0.9134401790298146 -1.1964413383803545 -0.39582550780613057
  0.149128168

In [27]:
print(X_test)

[[1.0 0.0 -0.45872338519496236 -0.08284740205303205 0.6925197395216028
  0.9967004924002616]
 [1.0 0.0 -0.23457097156104298 -0.015335865376060001 -0.20589225434800212
  -0.8140221990295581]
 [1.0 0.0 -0.2549642822875564 0.05415106145759207 -0.010677117443729218
  -0.15907994893792132]
 [1.0 0.0 0.03652781778971548 -1.023863621963357 0.7521368223196426
  1.3049086100904441]
 [1.0 0.0 0.1780629623711701 -0.9801537150422965 0.5067935435414783
  -0.4287620519168304]
 [0.0 1.0 0.9717316388709607 -1.4594955054870988 -0.2609944461940403
  1.3434346248017166]
 [1.0 0.0 -1.1162510522030744 0.7832812150904399 0.9350412114547664
  -0.8140221990295581]
 [1.0 0.0 1.481320800932979 0.24873656317750176 -2.4458938334895155
  0.9196484629777164]
 [0.0 1.0 1.1846781718667605 -0.3716995841537457 -1.4879160624008687
  0.1876541834635337]
 [0.0 1.0 0.41742335687110554 -1.0131042602597105 0.1815674782602586
  0.45733628644244345]
 [0.0 1.0 -0.5507020886935564 -0.015335865376060001 0.3891498508943979
  -1.00