## **Import library**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## **Import dataset**

In [2]:
dataset = pd.read_csv('data.csv')

In [3]:
print(dataset.head())

   Number Sex  %Red Pixel  %Green pixel  %Blue pixel    Hb Anaemic
0       1   M     43.2555       30.8421      25.9025   6.3     Yes
1       2   F     45.6033       28.1900      26.2067  13.5      No
2       3  F      45.0107       28.9677      26.0215  11.7      No
3       4   F     44.5398       28.9899      26.4703  13.5      No
4       5  M      43.2870       30.6972      26.0158  12.4      No


In [4]:
# Memisahkan fitur (X) dan target (y)
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[['M' 43.2555 30.8421 25.9025 6.3]
 ['F' 45.6033 28.19 26.2067 13.5]
 ['F ' 45.0107 28.9677 26.0215 11.7]
 ['F' 44.5398 28.9899 26.4703 13.5]
 ['M ' 43.287 30.6972 26.0158 12.4]
 ['M' 45.0994 27.9645 26.9361 16.2]
 ['F' 43.1457 30.1628 26.6915 8.6]
 ['F ' 43.6103 29.1099 27.2798 10.3]
 ['F' 45.0423 29.166 25.7918 13.0]
 ['F' 46.5143 27.4282 26.0575 9.7]
 ['F' 45.3506 29.1248 25.5246 12.6]
 ['F' 44.4062 28.9298 26.664 15.4]
 ['F' 44.9642 30.5279 24.5079 4.8]
 ['M ' 45.0484 31.1049 23.8467 9.0]
 ['M ' 46.9942 26.0496 26.9562 14.6]
 ['M' 45.5842 28.7311 25.6848 14.0]
 ['F' 42.5358 30.1604 27.3039 10.0]
 ['F' 44.0957 29.9973 25.907 8.3]
 ['F' 45.7104 27.5693 26.7204 13.6]
 ['F ' 40.9365 31.9687 27.0948 9.9]
 ['F' 44.9116 30.3761 24.7123 11.6]
 ['F ' 43.4225 29.7889 26.7886 12.4]
 ['F' 43.3019 29.8285 26.8697 12.1]
 ['F ' 47.6372 26.7953 25.5675 15.1]
 ['M' 45.6906 30.0735 24.2359 9.1]
 ['M ' 43.4098 31.2315 25.3586 12.9]
 ['F' 44.4252 28.7436 26.8312 14.7]
 ['M' 44.3297 28.7617 26.9086 14.

In [6]:
print(y)

['Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No']


In [7]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Number        104 non-null    int64  
 1   Sex           104 non-null    object 
 2   %Red Pixel    104 non-null    float64
 3   %Green pixel  104 non-null    float64
 4   %Blue pixel   104 non-null    float64
 5   Hb            104 non-null    float64
 6   Anaemic       104 non-null    object 
dtypes: float64(4), int64(1), object(2)
memory usage: 5.8+ KB
None


In [8]:
# periksa nilai yang hilang di setiap kolom
print(dataset.isnull().sum())

Number          0
Sex             0
%Red Pixel      0
%Green pixel    0
%Blue pixel     0
Hb              0
Anaemic         0
dtype: int64


Dataset ini tidak memiliki nilai yang hilang. Semua kolom memiliki data yang lengkap, sehingga dapat melanjutkan analisis dan pemodelan lebih lanjut tanpa perlu mengisi nilai yang hilang.

## **Encoding data kategori (Atribut)**

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#ubah kolom Sex bertipe string ke nuemrik
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[0.0 0.0 1.0 0.0 43.2555 30.8421 25.9025 6.3]
 [1.0 0.0 0.0 0.0 45.6033 28.19 26.2067 13.5]
 [0.0 1.0 0.0 0.0 45.0107 28.9677 26.0215 11.7]
 [1.0 0.0 0.0 0.0 44.5398 28.9899 26.4703 13.5]
 [0.0 0.0 0.0 1.0 43.287 30.6972 26.0158 12.4]
 [0.0 0.0 1.0 0.0 45.0994 27.9645 26.9361 16.2]
 [1.0 0.0 0.0 0.0 43.1457 30.1628 26.6915 8.6]
 [0.0 1.0 0.0 0.0 43.6103 29.1099 27.2798 10.3]
 [1.0 0.0 0.0 0.0 45.0423 29.166 25.7918 13.0]
 [1.0 0.0 0.0 0.0 46.5143 27.4282 26.0575 9.7]
 [1.0 0.0 0.0 0.0 45.3506 29.1248 25.5246 12.6]
 [1.0 0.0 0.0 0.0 44.4062 28.9298 26.664 15.4]
 [1.0 0.0 0.0 0.0 44.9642 30.5279 24.5079 4.8]
 [0.0 0.0 0.0 1.0 45.0484 31.1049 23.8467 9.0]
 [0.0 0.0 0.0 1.0 46.9942 26.0496 26.9562 14.6]
 [0.0 0.0 1.0 0.0 45.5842 28.7311 25.6848 14.0]
 [1.0 0.0 0.0 0.0 42.5358 30.1604 27.3039 10.0]
 [1.0 0.0 0.0 0.0 44.0957 29.9973 25.907 8.3]
 [1.0 0.0 0.0 0.0 45.7104 27.5693 26.7204 13.6]
 [0.0 1.0 0.0 0.0 40.9365 31.9687 27.0948 9.9]
 [1.0 0.0 0.0 0.0 44.9116 30.3761 24.7123 11.6]
 [0.0

## **Encoding data kategori (Label)**

In [11]:
from sklearn.preprocessing import LabelEncoder
# Encoding target "Anaemic" menggunakan LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0
 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0]


## **Membagi dataset ke dalam training set dan test set**

In [13]:
from sklearn.model_selection import train_test_split

# test_size = 0.2 berarti 20% dari data akan digunakan untuk pengujian
# random_state = 0 untuk memastikan hasil yang konsisten setiap kali kode dijalankan
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [14]:
print(X_train)

[[1.0 0.0 0.0 0.0 42.5892 31.5405 25.8703 9.0]
 [1.0 0.0 0.0 0.0 44.5398 28.9899 26.4703 13.5]
 [0.0 0.0 0.0 1.0 44.72 28.0357 27.2443 14.0]
 [1.0 0.0 0.0 0.0 43.1335 29.3459 27.5206 10.4]
 [0.0 0.0 1.0 0.0 53.9113 26.3455 19.7433 14.5]
 [1.0 0.0 0.0 0.0 43.1457 30.1628 26.6915 8.6]
 [0.0 0.0 1.0 0.0 46.7979 28.1768 25.0253 14.0]
 [1.0 0.0 0.0 0.0 50.4801 25.1403 24.3796 11.5]
 [0.0 1.0 0.0 0.0 44.3346 30.4043 25.2611 8.0]
 [0.0 0.0 0.0 1.0 43.4837 30.7106 25.8057 10.5]
 [0.0 0.0 1.0 0.0 48.3681 26.922 24.7099 12.5]
 [0.0 1.0 0.0 0.0 46.3745 28.882 24.7435 10.7]
 [0.0 0.0 0.0 1.0 41.133 32.3681 26.4989 10.0]
 [0.0 1.0 0.0 0.0 47.1003 28.3195 24.5801 12.4]
 [0.0 0.0 1.0 0.0 44.3297 28.7617 26.9086 14.1]
 [1.0 0.0 0.0 0.0 45.7104 27.5693 26.7204 13.6]
 [0.0 1.0 0.0 0.0 50.3562 29.2206 20.4232 11.9]
 [0.0 0.0 1.0 0.0 48.8763 29.4806 21.6431 12.5]
 [0.0 1.0 0.0 0.0 43.9224 29.8338 26.2437 12.1]
 [0.0 0.0 0.0 1.0 47.7549 26.2457 25.9994 15.2]
 [1.0 0.0 0.0 0.0 43.5706 29.8094 26.6199 12.2]


In [15]:
print(X_test)

[[1.0 0.0 0.0 0.0 44.4252 28.7436 26.8312 14.7]
 [0.0 1.0 0.0 0.0 45.0693 29.8506 25.0801 10.0]
 [0.0 1.0 0.0 0.0 45.0107 28.9677 26.0215 11.7]
 [0.0 1.0 0.0 0.0 45.8483 27.2043 26.9474 15.5]
 [1.0 0.0 0.0 0.0 46.255 27.2758 26.4692 11.0]
 [0.0 0.0 0.0 1.0 48.5356 26.4917 24.9727 15.6]
 [1.0 0.0 0.0 0.0 42.5358 30.1604 27.3039 10.0]
 [0.0 1.0 0.0 0.0 49.9999 29.286 20.7141 14.5]
 [0.0 0.0 1.0 0.0 49.1475 28.2711 22.5813 12.6]
 [0.0 0.0 0.0 1.0 46.9428 27.2219 25.8353 13.3]
 [0.0 0.0 0.0 1.0 44.1609 29.5993 26.2399 9.5]
 [1.0 0.0 0.0 0.0 51.5802 28.2678 20.152 13.2]
 [0.0 0.0 1.0 0.0 44.0418 28.5164 27.4418 11.9]
 [0.0 0.0 0.0 1.0 45.0484 31.1049 23.8467 9.0]
 [0.0 1.0 0.0 0.0 43.6103 29.1099 27.2798 10.3]
 [0.0 0.0 1.0 0.0 44.2572 29.6578 26.085 12.9]
 [1.0 0.0 0.0 0.0 43.3019 29.8285 26.8697 12.1]
 [0.0 0.0 1.0 0.0 45.6906 30.0735 24.2359 9.1]
 [0.0 0.0 1.0 0.0 45.4434 28.3301 26.2265 14.5]
 [1.0 0.0 0.0 0.0 45.0423 29.166 25.7918 13.0]
 [0.0 0.0 0.0 1.0 44.9526 28.4671 26.5803 13.1]]

In [16]:
print(y_train)

[1 0 0 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0
 0 0 0 1 1 0 1 0 0]


In [17]:
print(y_test)

[0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0]


## **Feature Scaling**

In [18]:
from sklearn.preprocessing import StandardScaler
# Menerapkan standarisasi pada fitur numerik (mulai dari kolom ke-5)
scaler = StandardScaler()
X_train[:, 4:] = scaler.fit_transform(X_train[:, 4:])
X_test[:, 4:] = scaler.transform(X_test[:,  4:])

In [19]:
print(X_train)

[[1.0 0.0 0.0 0.0 -1.0386257968950865 1.622462828356448
  0.19497335679704936 -1.1975885640243087]
 [1.0 0.0 0.0 0.0 -0.3719616062976776 0.06406868403143649
  0.500048046637602 0.5281032903857192]
 [0.0 0.0 0.0 1.0 -0.31037394755387954 -0.518939115119714
  0.8935943965319127 0.7198468297646112]
 [1.0 0.0 0.0 0.0 -0.8525982571933695 0.2815815497805567
  1.0340812912034882 -0.6607066537634111]
 [0.0 0.0 1.0 0.0 2.8309725996818216 -1.5516364344712892
  -2.9203476842913867 0.9115903691435032]
 [1.0 0.0 0.0 0.0 -0.8484286154804153 0.7807002577312746
  0.6125189156254853 -1.3509833955274224]
 [0.0 0.0 1.0 0.0 0.3997980619008291 -0.4327282573747673
  -0.2346734980617274 0.7198468297646112]
 [1.0 0.0 0.0 0.0 1.6582779566090105 -2.288003023799488
  -0.5629847101118022 -0.23887086712984876]
 [0.0 1.0 0.0 0.0 -0.44209361281392223 0.9282546315470386
  -0.11477914495439172 -1.5810756427820927]
 [0.0 0.0 0.0 1.0 -0.7329090335969309 1.1154012348587108
  0.16212698185755062 -0.6223579458876328]
 [0.0 

In [20]:
print(X_test)

[[1.0 0.0 0.0 0.0 -0.41112889648657586 -0.0864184475247647
  0.6835504725766927 0.9882877848950598]
 [0.0 1.0 0.0 0.0 -0.19099232047724957 0.5899488063636478
  -0.20681000972295688 -0.8141014852665248]
 [0.0 1.0 0.0 0.0 -0.2110202716558649 0.050504679481913985
  0.2718521786368681 -0.16217345137829223]
 [0.0 1.0 0.0 0.0 0.0752495561122016 -1.026917195411336
  0.7426332708424792 1.2950774479012872]
 [1.0 0.0 0.0 0.0 0.2142490056743704 -0.9832313249027346
  0.49948874303956053 -0.4306144065087408]
 [0.0 0.0 0.0 1.0 0.9936985868680798 -1.4623095216271282
  -0.2614183792044167 1.3334261557770655]
 [1.0 0.0 0.0 0.0 -1.0568765237370321 0.7792338788610549
  0.9238984823894074 -0.8141014852665248]
 [0.0 1.0 0.0 0.0 1.4941581245958462 0.24498317714468026
  -2.426736836129375 0.9115903691435032]
 [0.0 0.0 1.0 0.0 1.202830042946493 -0.37511178759908737
  -1.477344401345577 0.1829649195037135]
 [0.0 0.0 0.0 1.0 0.4493211015899321 -1.016163750363064
  0.1771773332230171 0.4514058746341627]
 [0.0 0.