In [1]:
# Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
# Membaca Dataset dari File ke Pandas dataFrame
Dataset = pd.read_csv('dataset/lung cancer data.csv')

In [3]:
# Mengubah kelas (kolom "Lung Cancer") dari String ke Unique-Integer
Dataset["LUNG_CANCER"] = pd.factorize(Dataset.LUNG_CANCER)[0]

In [4]:
# Mengubah dataFrame ke array Numpy
Dataset = Dataset.to_numpy()

In [5]:
#Membagi Dataset => 80 baris data untuk training dan 20 baris data untuk testing
# dataTraining = np.concatenate((Dataset[0:40, :], Dataset[50:90, :]), 
#                               axis=0)
# dataTesting = np.concatenate((Dataset[40:50, :], Dataset[90:100, :]), 
#                              axis=0)


In [6]:
from sklearn.model_selection import train_test_split
# Membagi dataset menjadi 80% untuk pelatihan dan 20% untuk pengujian
dataTraining, dataTesting = train_test_split(Dataset, test_size=0.2, random_state=0)

# Menampilkan bentuk dataTraining dan dataTesting
print("Bentuk dataTraining:", dataTraining.shape)  
print("Bentuk dataTesting:", dataTesting.shape)   

Bentuk dataTraining: (247, 16)
Bentuk dataTesting: (62, 16)


In [7]:
#Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:15]
inputTesting = dataTesting[:, 0:15]
labelTraining = dataTraining[:, 15]
labelTesting = dataTesting[:, 15]

In [8]:
print(labelTraining)
print(type(labelTraining))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


In [9]:
# Membulatkan labelTraining
labelTraining = labelTraining.astype(int)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
inputTraining = np.array(ct.fit_transform(inputTraining))
inputTesting = np.array(ct.transform(inputTesting))  # Hanya transformasi, tidak fit ulang

In [11]:
print("Hasil transformasi inputTraining:")
print(inputTraining)

Hasil transformasi inputTraining:
[[1.0 0.0 51 ... 2 2 1]
 [0.0 1.0 72 ... 2 2 2]
 [0.0 1.0 59 ... 2 1 1]
 ...
 [1.0 0.0 51 ... 2 2 1]
 [1.0 0.0 64 ... 1 2 2]
 [0.0 1.0 56 ... 1 1 1]]


In [12]:
# Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [13]:
# Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [14]:
# Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0]
Hasil Prediksi :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [15]:
# Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 56 data
Prediksi Salah : 6 data
Akurasi : 90.32258064516128 %
